#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##  Important for running: use JDK 17+ for this project.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%/*}
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in
      /*) app_path=$link ;;
      *) app_path=$APP_HOME/$link ;;
    esac
done

APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  MINGW* ) msys=true ;;
  Darwin* ) darwin=true ;;
  NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine Java version and ensure JAVA_HOME set
if [ -z "$JAVA_HOME" ]; then
  warn "Please set JAVA_HOME (JDK 17+)"
fi

# Increase the maximum file descriptors if we can.
if ! $cygwin && ! $darwin && ! $nonstop ; then
  case $MAX_FD in
    max*)
      MAX_FD=$(ulimit -H -n)
      if [ $? -ne 0 ]; then MAX_FD=; fi
    ;;
  esac
  if [ -n "$MAX_FD" ]; then
    ulimit -n $MAX_FD
  fi
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
# from POSIX sh.

save () {
  for i do printf %s\\n "$i" | sed "s/'/'\\''/g;1s/^/'/;
    $s/$/' \\"; done
  echo ""
}
APP_ARGS=$(save "$@")

# Collect environment variables and JVM system properties.
CLASSPATH=$CLASSPATH

# Execute Gradle
exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -Dorg.gradle.appname=$APP_BASE_NAME \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
